In [1]:
import pandas as pd
import requests
import yfinance as yf
def fetch_data(ticker, start_date = None, end_date = None, interval = "1d"):
    stock = yf.Ticker(ticker)
    ohlcv_df = stock.history(start = start_date, end = end_date, interval = interval)
    ohlcv_df_clean = ohlcv_df.dropna()
    return ohlcv_df_clean

data = fetch_data("KO", "2020-01-01", "2024-12-31")
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,47.377360,47.471567,46.897761,47.094742,11867700,0.0,0.0
2020-01-03 00:00:00-05:00,46.520935,47.094740,46.323958,46.837811,11354500,0.0,0.0
2020-01-06 00:00:00-05:00,46.803553,47.026222,46.692217,46.820679,14698300,0.0,0.0
2020-01-07 00:00:00-05:00,46.632265,46.760726,46.375338,46.460979,9973900,0.0,0.0
2020-01-08 00:00:00-05:00,46.478100,46.794975,46.375330,46.546612,10676000,0.0,0.0

In [3]:
def fetch_news_articles(ticker, from_date = None, to_date = None, language = "en", page_size = 100):
    url = "https://newsapi.org/v2/everything"
    params = {
        "q": ticker,
        "apiKey": "6920c0ee94ef49539a8c84af9ed1ea58",
        "language": language,
        "pageSize": page_size,
        "from": from_date,
        "to": to_date,
        "sortBy": "relevancy"
    }
    response = requests.get(url, params = params)
    data = response.json()
    if data.get("status") == "ok":
        articles = data.get("articles", [])
        news_df = pd.DataFrame(articles)[["publishedAt", "title", "description", "url", "content"]]
        news_df["publishedAt"] = pd.to_datetime(news_df["publishedAt"])
        return news_df
    else:
        raise Exception(f"Error fetching news: {data.get('message', 'Unknown error')}")

In [6]:
news_df = fetch_news_articles("GOOG", "2025-02-04", "2025-03-03")
news_df

,publishedAt,title,description,url,content
0,2025-02-05 22:35:00+00:00,"Big Tech's AI spending, Treasury yields plunge...","US stocks (^GSPC, ^IXIC, ^DJI) closed higher a...",https://finance.yahoo.com/video/big-techs-ai-s...,"US stocks (^GSPC, ^IXIC, ^DJI) closed higher a..."
1,2025-02-06 16:09:08+00:00,What's Happening With GOOG Stock?,Although Google continued to benefit from its ...,https://www.forbes.com/sites/greatspeculations...,"SUQIAN, CHINA - FEBRUARY 05: In this photo ill..."
2,2025-02-04 17:15:00+00:00,Now generally available: Easily migrate files ...,"What’s changing In October 2024, we expanded o...",http://workspaceupdates.googleblog.com/2025/02...,"What’s changingIn October 2024, we expanded ou..."
3,2025-02-12 11:19:42+00:00,"Leaking the email of any YouTube user for $10,000",What could've been the largest data breach in ...,https://brutecat.com/articles/leaking-youtube-...,"&lt; Back2025-02-12\r\nSome time ago, I was lo..."
4,2025-02-25 18:53:54+00:00,Why GOOG Stock Is Dropping Today,None,https://consent.yahoo.com/v2/collectConsent?se...,"If you click 'Accept all', we and our partners..."
...,...,...,...,...,...
95,2025-02-05 11:26:52+00:00,Coerente Capital Management Cuts Position in A...,Coerente Capital Management trimmed its holdin...,https://www.etfdailynews.com/2025/02/05/coeren...,Coerente Capital Management trimmed its holdin...
96,2025-02-05 11:26:50+00:00,Concord Asset Management LLC VA Sells 285 Shar...,Concord Asset Management LLC VA decreased its ...,https://www.etfdailynews.com/2025/02/05/concor...,Concord Asset Management LLC VA decreased its ...
97,2025-02-07 09:14:48+00:00,Deepwater Asset Management LLC Trims Stock Hol...,Deepwater Asset Management LLC decreased its h...,https://www.etfdailynews.com/2025/02/07/deepwa...,Deepwater Asset Management LLC decreased its h...
98,2025-02-16 08:40:57+00:00,TFB Advisors LLC Has $1.48 Million Stake in Al...,TFB Advisors LLC trimmed its position in share...,https://www.etfdailynews.com/2025/02/16/tfb-ad...,TFB Advisors LLC trimmed its position in share...
99,2025-02-19 11:04:56+00:00,Scarborough Advisors LLC Buys 527 Shares of Al...,Scarborough Advisors LLC boosted its stake in ...,https://www.etfdailynews.com/2025/02/19/scarbo...,Scarborough Advisors LLC boosted its stake in ...